name: 28541 Testiranje kode

on:
  push:
    branches:
      - main

jobs:
  preveri_teste:
    runs-on: ubuntu-latest
    outputs:
      testi_obstajajo: ${{ steps.check_tests.outputs.exists }}
    steps:
      - name: Kloniraj repozitorij
        uses: actions/checkout@v4

      - name: Preveri obstoj testnih skript
        id: check_tests
        run: |
          if [ -z "$(find . -name 'test_*.py')" ]; then
            echo "Napaka: Testne skripte ne obstajajo!" >&2
            echo "Testi manjkajo." > napaka.txt
            echo "::set-output name=exists::false"
          else
            echo "Testne skripte obstajajo."
            echo "" > napaka.txt
            echo "::set-output name=exists::true"
          fi

      - name: Shranjevanje napake kot artefakt
        uses: actions/upload-artifact@v4
        with:
          name: napaka
          path: napaka.txt

  poganjaj_teste:
    needs: preveri_teste
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9, 3.10]  # << tukaj je matrica
    steps:
      - name: Kloniraj repozitorij
        uses: actions/checkout@v4

      - name: Prenesi napaka.txt
        uses: actions/download-artifact@v4
        with:
          name: napaka

      - name: Preveri napako in prekini če obstaja
        run: |
          if [ -s napaka.txt ]; then
            echo "Testi manjkajo ali pa je prišlo do napake:"
            cat napaka.txt
            exit 1
          fi

      - name: Nastavi Python okolje
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Namesti odvisnosti
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Poženi teste
        run: pytest
