name: 28541_deploy

on:
  workflow_run:
    workflows: ["28541_test"]
    types:
      - completed
    branches:
      - main

jobs:
  build-and-push:
    runs-on: self-hosted
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Kloniraj repozitorij
        uses: actions/checkout@v4

      - name: Nastavi Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Prijava v DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Generiraj metapodatke
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/orv-face-detection
          tags: |
            type=raw,value=latest
            type=sha,format=short

      - name: Zgradi in objavi Docker sliko
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/orv-face-detection:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/orv-face-detection:buildcache,mode=max
