name: 28541 Deploy aplikacije

on:
  workflow_run:
    workflows: ["28541 Testiranje kode"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Kloniraj repozitorij
        uses: actions/checkout@v4

      - name: Prijava v DockerHub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Zgradi Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/orv-app:latest .

      - name: Potisni image na DockerHub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/orv-app:latest
